//
// Generated file, do not edit! Created by opp_msgc 4.2 from DistanceMessage.msg.
//

#ifndef _DISTANCEMESSAGE_M_H_
#define _DISTANCEMESSAGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>DistanceMessage.msg</tt> by opp_msgc.
 * <pre>
 * message DistanceMessage
 * {
 *     int idSrb[];
 *     double distances[];
 * }
 * </pre>
 */
class DistanceMessage : public ::cMessage
{
  protected:
    int *idSrb_var; // array ptr
    unsigned int idSrb_arraysize;
    double *distances_var; // array ptr
    unsigned int distances_arraysize;

  private:
    void copy(const DistanceMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const DistanceMessage&);

  public:
    DistanceMessage(const char *name=NULL, int kind=0);
    DistanceMessage(const DistanceMessage& other);
    virtual ~DistanceMessage();
    DistanceMessage& operator=(const DistanceMessage& other);
    virtual DistanceMessage *dup() const {return new DistanceMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual void setIdSrbArraySize(unsigned int size);
    virtual unsigned int getIdSrbArraySize() const;
    virtual int getIdSrb(unsigned int k) const;
    virtual void setIdSrb(unsigned int k, int idSrb);
    virtual void setDistancesArraySize(unsigned int size);
    virtual unsigned int getDistancesArraySize() const;
    virtual double getDistances(unsigned int k) const;
    virtual void setDistances(unsigned int k, double distances);
};

inline void doPacking(cCommBuffer *b, DistanceMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, DistanceMessage& obj) {obj.parsimUnpack(b);}


#endif // _DISTANCEMESSAGE_M_H_
