//
// Generated file, do not edit! Created by opp_msgc 4.2 from HandoverUpdate.msg.
//

#ifndef _HANDOVERUPDATE_M_H_
#define _HANDOVERUPDATE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>HandoverUpdate.msg</tt> by opp_msgc.
 * <pre>
 * message HandoverUpdate
 * {
 *     int idMs;
 *     int idDriftSrb;
 * }
 * </pre>
 */
class HandoverUpdate : public ::cMessage
{
  protected:
    int idMs_var;
    int idDriftSrb_var;

  private:
    void copy(const HandoverUpdate& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const HandoverUpdate&);

  public:
    HandoverUpdate(const char *name=NULL, int kind=0);
    HandoverUpdate(const HandoverUpdate& other);
    virtual ~HandoverUpdate();
    HandoverUpdate& operator=(const HandoverUpdate& other);
    virtual HandoverUpdate *dup() const {return new HandoverUpdate(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getIdMs() const;
    virtual void setIdMs(int idMs);
    virtual int getIdDriftSrb() const;
    virtual void setIdDriftSrb(int idDriftSrb);
};

inline void doPacking(cCommBuffer *b, HandoverUpdate& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, HandoverUpdate& obj) {obj.parsimUnpack(b);}


#endif // _HANDOVERUPDATE_M_H_
