//
// Generated file, do not edit! Created by opp_msgc 4.2 from HelloMessage.msg.
//

#ifndef _HELLOMESSAGE_M_H_
#define _HELLOMESSAGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>HelloMessage.msg</tt> by opp_msgc.
 * <pre>
 * message HelloMessage
 * {
 *     int idSRB;
 *     double frequenzaCanalePilota;
 *     double frequenzaCanaleDati;
 *     double frequenzaCanaleSegnalazione;
 * }
 * </pre>
 */
class HelloMessage : public ::cMessage
{
  protected:
    int idSRB_var;
    double frequenzaCanalePilota_var;
    double frequenzaCanaleDati_var;
    double frequenzaCanaleSegnalazione_var;

  private:
    void copy(const HelloMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const HelloMessage&);

  public:
    HelloMessage(const char *name=NULL, int kind=0);
    HelloMessage(const HelloMessage& other);
    virtual ~HelloMessage();
    HelloMessage& operator=(const HelloMessage& other);
    virtual HelloMessage *dup() const {return new HelloMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getIdSRB() const;
    virtual void setIdSRB(int idSRB);
    virtual double getFrequenzaCanalePilota() const;
    virtual void setFrequenzaCanalePilota(double frequenzaCanalePilota);
    virtual double getFrequenzaCanaleDati() const;
    virtual void setFrequenzaCanaleDati(double frequenzaCanaleDati);
    virtual double getFrequenzaCanaleSegnalazione() const;
    virtual void setFrequenzaCanaleSegnalazione(double frequenzaCanaleSegnalazione);
};

inline void doPacking(cCommBuffer *b, HelloMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, HelloMessage& obj) {obj.parsimUnpack(b);}


#endif // _HELLOMESSAGE_M_H_
