//
// Generated file, do not edit! Created by opp_msgc 4.2 from NetworkAccessRequestMessage.msg.
//

#ifndef _NETWORKACCESSREQUESTMESSAGE_M_H_
#define _NETWORKACCESSREQUESTMESSAGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>NetworkAccessRequestMessage.msg</tt> by opp_msgc.
 * <pre>
 * message NetworkAccessRequestMessage
 * {
 *     int idMS;
 *     int idDesideredSRB;
 * }
 * </pre>
 */
class NetworkAccessRequestMessage : public ::cMessage
{
  protected:
    int idMS_var;
    int idDesideredSRB_var;

  private:
    void copy(const NetworkAccessRequestMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const NetworkAccessRequestMessage&);

  public:
    NetworkAccessRequestMessage(const char *name=NULL, int kind=0);
    NetworkAccessRequestMessage(const NetworkAccessRequestMessage& other);
    virtual ~NetworkAccessRequestMessage();
    NetworkAccessRequestMessage& operator=(const NetworkAccessRequestMessage& other);
    virtual NetworkAccessRequestMessage *dup() const {return new NetworkAccessRequestMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getIdMS() const;
    virtual void setIdMS(int idMS);
    virtual int getIdDesideredSRB() const;
    virtual void setIdDesideredSRB(int idDesideredSRB);
};

inline void doPacking(cCommBuffer *b, NetworkAccessRequestMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, NetworkAccessRequestMessage& obj) {obj.parsimUnpack(b);}


#endif // _NETWORKACCESSREQUESTMESSAGE_M_H_
