//
// Generated file, do not edit! Created by opp_msgc 4.2 from NetworkAccessConfirmationMessage.msg.
//

#ifndef _NETWORKACCESSCONFIRMATIONMESSAGE_M_H_
#define _NETWORKACCESSCONFIRMATIONMESSAGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>NetworkAccessConfirmationMessage.msg</tt> by opp_msgc.
 * <pre>
 * message NetworkAccessConfirmationMessage
 * {
 *     int idSrb;
 *     int idMs;
 * }
 * </pre>
 */
class NetworkAccessConfirmationMessage : public ::cMessage
{
  protected:
    int idSrb_var;
    int idMs_var;

  private:
    void copy(const NetworkAccessConfirmationMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const NetworkAccessConfirmationMessage&);

  public:
    NetworkAccessConfirmationMessage(const char *name=NULL, int kind=0);
    NetworkAccessConfirmationMessage(const NetworkAccessConfirmationMessage& other);
    virtual ~NetworkAccessConfirmationMessage();
    NetworkAccessConfirmationMessage& operator=(const NetworkAccessConfirmationMessage& other);
    virtual NetworkAccessConfirmationMessage *dup() const {return new NetworkAccessConfirmationMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getIdSrb() const;
    virtual void setIdSrb(int idSrb);
    virtual int getIdMs() const;
    virtual void setIdMs(int idMs);
};

inline void doPacking(cCommBuffer *b, NetworkAccessConfirmationMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, NetworkAccessConfirmationMessage& obj) {obj.parsimUnpack(b);}


#endif // _NETWORKACCESSCONFIRMATIONMESSAGE_M_H_
