//
// Generated file, do not edit! Created by opp_msgc 4.2 from PresenceMessage.msg.
//

#ifndef _PRESENCEMESSAGE_M_H_
#define _PRESENCEMESSAGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>PresenceMessage.msg</tt> by opp_msgc.
 * <pre>
 * message PresenceMessage
 * {
 *     int idMs;
 * }
 * </pre>
 */
class PresenceMessage : public ::cMessage
{
  protected:
    int idMs_var;

  private:
    void copy(const PresenceMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PresenceMessage&);

  public:
    PresenceMessage(const char *name=NULL, int kind=0);
    PresenceMessage(const PresenceMessage& other);
    virtual ~PresenceMessage();
    PresenceMessage& operator=(const PresenceMessage& other);
    virtual PresenceMessage *dup() const {return new PresenceMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getIdMs() const;
    virtual void setIdMs(int idMs);
};

inline void doPacking(cCommBuffer *b, PresenceMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, PresenceMessage& obj) {obj.parsimUnpack(b);}


#endif // _PRESENCEMESSAGE_M_H_
