//
// Generated file, do not edit! Created by opp_msgc 4.2 from RegistrationMessage.msg.
//

#ifndef _REGISTRATIONMESSAGE_M_H_
#define _REGISTRATIONMESSAGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>RegistrationMessage.msg</tt> by opp_msgc.
 * <pre>
 * message RegistrationMessage
 * {
 *     int idMS;
 *     int idSRB;
 * }
 * </pre>
 */
class RegistrationMessage : public ::cMessage
{
  protected:
    int idMS_var;
    int idSRB_var;

  private:
    void copy(const RegistrationMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const RegistrationMessage&);

  public:
    RegistrationMessage(const char *name=NULL, int kind=0);
    RegistrationMessage(const RegistrationMessage& other);
    virtual ~RegistrationMessage();
    RegistrationMessage& operator=(const RegistrationMessage& other);
    virtual RegistrationMessage *dup() const {return new RegistrationMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getIdMS() const;
    virtual void setIdMS(int idMS);
    virtual int getIdSRB() const;
    virtual void setIdSRB(int idSRB);
};

inline void doPacking(cCommBuffer *b, RegistrationMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, RegistrationMessage& obj) {obj.parsimUnpack(b);}


#endif // _REGISTRATIONMESSAGE_M_H_
